import { expect, it } from "vitest";
import { IDBFactory } from "fake-indexeddb";
import { Game } from "../../src/domain/game";
import { createMatchConfig } from "../../src/domain/config";
import { GameSession } from "../../src/app/GameSession";
import { GameStore } from "../../src/storage/GameStore";
import { auctionView } from "../../src/ui/viewModel";
import { propertyMatchId } from "../fixtures/property-match";

const instant = { sync() {}, stop() {}, async present() {} };

it("persists bidding and final sale as separate atomic decisions, requiring handover after restore without moving the ordinary turn", async () => {
  const config = createMatchConfig(940);
  const game = new Game({ ...config, players: config.players.map((player) => ({ ...player, controller: "human" })) });
  for (const kind of ["roll", "skip"] as const) expect(game.apply({ kind, actor: "p1", expectedRevision: game.snapshot.revision }).ok).toBe(true);
  const factory = new IDBFactory();
  const repository = new GameStore(() => factory);
  const session = new GameSession(game, propertyMatchId, { store: repository, expected: null, source: "local" });
  await session.initializeSave();
  session.bind(instant);
  expect(session.handoverActor).toBe("p2");
  session.confirmHandover("p2");
  const bid = auctionView(session.getSnapshot())!.commands.find((command) => command.kind === "auction_bid")!;
  await session.dispatch(bid);
  const pending = game.snapshot;
  expect(pending.turnPlayerId).toBe("p1");
  expect(pending.decision).toMatchObject({ kind: "awaiting_auction", actorId: "p1", highestBid: 10, highestBidderId: "p2" });
  expect(pending.players.map((player) => player.cash)).toEqual([1500, 1500]);
  expect(session.getSnapshot().notice).toBeNull();
  expect((await repository.read())!.snapshot).toEqual(pending);
  session.dispose();
  const saved = (await repository.read())!;
  const restored = Game.restore(saved.record.state);
  const resumed = new GameSession(restored, propertyMatchId, { store: repository, expected: saved.record, source: "local" });
  await resumed.initializeSave();
  resumed.bind(instant);
  expect(resumed.handoverActor).toBe("p1");
  await resumed.dispatch({ kind: "auction_pass", actor: "p1", expectedRevision: pending.revision });
  expect(restored.snapshot).toEqual(pending);
  resumed.confirmHandover("p1");
  resumed.pause();
  await resumed.resume();
  const pass = auctionView(resumed.getSnapshot())!.commands.find((command) => command.kind === "auction_pass")!;
  await resumed.dispatch(pass);
  const final = restored.snapshot;
  expect(final.turnPlayerId).toBe("p2");
  expect(final.players[1]!.cash).toBe(1490);
  expect(final.properties["neon-avenue"]!.ownerId).toBe("p2");
  expect((await repository.read())!.snapshot).toEqual(final);
  expect((await repository.read("backup"))!.snapshot).toEqual(pending);
  expect(resumed.handoverActor).toBe("p2");
  expect(resumed.getSnapshot().notice?.event).toMatchObject({ kind: "auction_ended", winnerId: "p2", price: 10 });
  await resumed.dispatch(pass);
  expect(restored.snapshot).toBe(final);
  resumed.dispose();
});
